import{a as E,S as L,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const S="48961514-d720aad073d42be14fd4daf93",v="https://pixabay.com/api/";async function y(o,s=1){try{const t=await E.get(v,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:40}});return{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){return console.error("Error fetching images:",t),iziToast.error({message:"An error occurred while fetching images. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),{images:[],totalHits:0}}}const f=document.querySelector(".gallery");let w=new L(".gallery a");function h(o,s){s===1&&F();const t=o.map(({webformatURL:i,largeImageURL:e,tags:r,likes:c,views:b,comments:A,downloads:C})=>`
        <li class="img-card">
            <a href="${e}">
                <img 
                    src="${i}" 
                    alt="${r}" 
                    data-source="${e}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${c}</p>
                <p><strong>Views:</strong> ${b}</p>
                <p><strong>Comments:</strong> ${A}</p>
                <p><strong>Downloads:</strong> ${C}</p>
            </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),w.refresh()}function F(){f.innerHTML=""}const d=document.querySelector("form"),u=document.querySelector(".loader"),p=document.querySelector(".loader-bottom"),n=document.querySelector(".btn-loadmore");let a=1,m="",g="";d.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.querySelector("input").value.trim();if(t===""){l.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}g=t,t!==m&&(a=1,m=t,F()),u.style.display="block",n.style.display="none";try{const{images:i,totalHits:e}=await y(g,a);if(!i||i.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}h(i,a),a*40>=e?(n.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):n.style.display="block",a++}catch{l.error({message:"Error fetching images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{u.style.display="none"}d.reset()});n.addEventListener("click",async()=>{n.style.display="none",p.style.display="block";try{const{images:o,totalHits:s}=await y(g,a);o&&o.length>0&&(h(o,a),a++,a*40>=s?(n.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):n.style.display="block",k())}catch{l.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{p.style.display="none"}});function k(){const o=document.querySelector(".img-card");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
